# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gustavoquinalha
email: gustavo_quinalha@hotmail.com
description: > # blog utilizando jekyll teste.
baseurl: "" 
url: "https://gustavoquinalha.github.io"
twitter_username: gustavoquinalha
github_username:  gustavoquinalha

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title
permalink: /:year/:title
